### PR TITLE
move sharp to peerDependencies

### LINKED ISSUE #2: Possible to include sharp as optional/peer dependency?
Hi!

I've been having an issue including `smartcrop-sharp` in a docker image because `sharp 0.16.2` is failing to build. The thing is `sharp 0.18.x` is working fine so it's not necessary to install `0.16.2`. Could the dependency be changed to prevent this unnecessary  double installation?

Thanks

### LINKED ISSUE #4: Upgrade sharp version?
I ran into an interesting bug during deploy. Since my sharp dependency is more modern that smartcrop-sharp, somehow only smartcrop's sharp version was installed, breaking my deploy on netlify. This is a sharp issue, but I figured since it's a non-breaking change, it might be worth doing here as well.

### PR DESCRIPTION
**Pull request by sylvaindumont**
closes #2, closes #4

### CODE REVIEW

**Comment by mikestopcontinues** [comment]
@jwagner, bump?

**Comment by jwagner** [comment]
Ci needs to be fixed & docs updated. I'll do it with the 2.0 release.

**Comment by sylvaindumont** [comment]
@jwagner ci fixed, docs updated, and sharp updated to 0.19

**Comment by jwagner** [comment]
@sylvaindumont 
Thanks! Smartcrop 2.0 is out so I'll update the node companion libraries in the coming days. Is there any reason not to add sharp as a dev dependency? That would get rid of the install statement in the travis config and would make it easier for people to hack on.

**Comment by sylvaindumont** [comment]
It didn't come to my mind that we can have sharp in both peer and dev dependencies, will add it :)

**Comment by jwagner** [comment]
Thank you!

**Comment by jwagner** [comment]
This has been released with the other changes in 2.0.2.

**Pull request merged**
