### PR TITLE
chore: updating sharp to 32.05

### PR DESCRIPTION
**Pull request by achepukov**
Can we update dependencies once again?

### CODE REVIEW

**Comment by jwagner** [comment]
Yes. Wondering whether it's worth to just set the peer dependency version to `*`.  It's wrong based on semver, in the sense that changes to sharp could break smartcrop-sharp but in practice I feel like the current process is worse.  There weren't any issues for something like 20 releases of sharp so far but a lot of grief because the library wasn't updated. I guess the alternative would be to automated the updating, which would at least run the tests but that's more work.

What do you think would be a good solution for the future @achepukov ? :)

**Comment by achepukov** [comment]
@jwagner thanks for quick merge, you Rock!  

Imo it's acceptable to use `*`, and point to the README.md that latest tested version was x.y.z or something. I guess you'll got an issue if any, and perhaps with PR.

In terms of the best solution - I agree that it should be auto tests + version bump for every sharp release. Can I help you with that?

**Comment by achepukov** [comment]
@jwagner could you please release latest main?

**Comment by achepukov** [comment]
@jwagner I mean publish 2.0.8

**Comment by achepukov** [comment]
Yeah, looks like last 3 - 4 releases you did only update sharp dependencies )))
I'm going to create PR to bind sharp to *
Screenshot 2023-08-23 at 15 43 59

**Comment by jwagner** [comment]
I'm currently traveling, will get back to this as soon as I'm back, likely next Monday. Sorry for the delay.

**Comment by achepukov** [comment]
@jwagner ok, have a great trip! )
[This](https://github.com/jwagner/smartcrop-sharp/pull/32) should resolve your pain regarding sharp updates

**Comment by achepukov** [comment]
@jwagner  may I hope for a release this week? :)
Again, feel free to ask for help if anything

**Comment by jwagner** [comment]
Hey @achepukov thank you for your patience! I had an accident during my vacation that I'm still recovering from. I'll try to release the dependency update today and review the PR semver change later when I have a bit more spare mental capacity.

**Comment by achepukov** [comment]
Thanks a lot Man! Take care! 👍

**Pull request merged**
