### PR TITLE
Add TypeScript declaration file

### LINKED ISSUE #10: [Feature Request] Typescript declaration file
very  handy and easy-to-use lib ! would you please provide Typescript declaration file for it ?
i have already searched in https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types but found nothing.

### PR DESCRIPTION
**Pull request by nicholaschiang**
Fixes #10.

### CODE REVIEW

**Comment by nicholaschiang** [comment]
@jwagner I also just noticed jwagner/smartcrop.js#100 and was wondering if you want to port some of that code over here (or vice versa) to make everything consistent.

**Comment by jwagner** [comment]
Thanks for the PR @nicholaschiang !

My experience in sharing typescript libraries is still quite limited but it seems like the best way would be to add your jsdoc comments to type in the main smartcrop package and to reuse those types in smartcrop-sharp except for the crop signature which differs. What do you think?

**Comment by nicholaschiang** [comment]
> Thanks for the PR @nicholaschiang !
> 
> My experience in sharing typescript libraries is still quite limited but it seems like the best way would be to add your jsdoc comments to type in the main smartcrop package and to reuse those types in smartcrop-sharp except for the crop signature which differs. What do you think?

Yeah, I was just grabbing those JSDoc comments from your README. Otherwise, the two type definitions are pretty much identical.

**Comment by nicholaschiang** [comment]
@jwagner Any chance you could merge and release this soon? Still relying on a `global.d.ts` file and it'd be nice to have them included with the NPM module itself. Thanks for your great work on this BTW!

**Comment by jwagner** [comment]
I've updated the MR to reuse the definitions from the smartcrop package where possible. Preparing a release now. Thank you for your patience!

**Pull request merged**
